from enum import IntEnum

class ActionType(IntEnum):
    #TURN
    PASS = 0
    WAIT = 1

    #CONVERSION
    HEAT_INTO_TEMPERATURE = 2
    PLANTS_INTO_GREENERY = 3

    #STANDARD_PROJECT
    SELL_PATENTS = 4
    POWER_PLANT = 5
    ASTEROID = 6
    AQUIFER = 7
    GREENERY = 8
    CITY = 9

    #CLAIM_MILESTONES
    CLAIM_TERRAFORMER = 10
    CLAIM_MAYOR = 11
    CLAIM_GARDENER = 12
    CLAIM_BUILDER = 13
    CLAIM_PLANNER = 14

    #FUND_AWARDS
    FUND_LANDLORD = 15
    FUND_BANKER = 16
    FUND_SCIENTIST = 17
    FUND_THERMALIST = 18
    FUND_MINER = 19

    # #CARD_PLAY
    # PLAY_CARD_SLOT_0 = 20
    # PLAY_CARD_SLOT_1 = 21
    # PLAY_CARD_SLOT_2 = 22
    # PLAY_CARD_SLOT_3 = 23
    # PLAY_CARD_SLOT_4 = 24
    # PLAY_CARD_SLOT_5 = 25
    # PLAY_CARD_SLOT_6 = 26
    # PLAY_CARD_SLOT_7 = 27
    # PLAY_CARD_SLOT_8 = 28
    # PLAY_CARD_SLOT_9 = 29

    # #CARD_ACTION
    # PLAY_CARD_ACTION_0 = 30
    # PLAY_CARD_ACTION_1 = 31
    # PLAY_CARD_ACTION_2 = 32
    # PLAY_CARD_ACTION_3 = 33
    # PLAY_CARD_ACTION_4 = 34