from enum import IntEnum

class ActionType(IntEnum):
    #TURN
    PASS = 0
    WAIT = 1

    #CONVERSION
    PLANTS_INTO_GREENERY = 2
    HEAT_INTO_TEMPERATURE = 3

    #CLAIM_MILESTONES
    CLAIM_TERRAFORMER = 4
    CLAIM_MAYOR = 5
    CLAIM_GARDENER = 6
    CLAIM_BUILDER = 7
    CLAIM_PLANNER = 8

    #FUND_AWARDS
    FUND_LANDLORD = 9
    FUND_BANKER = 10
    FUND_SCIENTIST = 11
    FUND_THERMALIST = 12
    FUND_MINER = 13

    #STANDARD_PROJECT
    SELL_PATENTS = 14
    POWER_PLANT = 15
    ASTEROID = 16
    AQUIFER = 17
    GREENERY = 18
    CITY = 19

    # #CARD_PLAY
    # PLAY_CARD_SLOT_0 = 20
    # PLAY_CARD_SLOT_1 = 21
    # PLAY_CARD_SLOT_2 = 22
    # PLAY_CARD_SLOT_3 = 23
    # PLAY_CARD_SLOT_4 = 24
    # PLAY_CARD_SLOT_5 = 25
    # PLAY_CARD_SLOT_6 = 26
    # PLAY_CARD_SLOT_7 = 27
    # PLAY_CARD_SLOT_8 = 28
    # PLAY_CARD_SLOT_9 = 29

    # #CARD_ACTION
    # PLAY_CARD_ACTION_0 = 30
    # PLAY_CARD_ACTION_1 = 31
    # PLAY_CARD_ACTION_2 = 32
    # PLAY_CARD_ACTION_3 = 33
    # PLAY_CARD_ACTION_4 = 34